### ISSUE TITLE
SDV ordnance tracking not functional

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1251]
#### Description of issue

Ordnance tracking with any weapons aboard the SDV corvette (pulse lasers and energy projector) doesn't work

#### Difference between expected and actual behaviour

Ordnance tracking should show us the projectile hitting/missing the target when turned on

#### Steps to reproduce 

Activate ordnance tracking on an SDV console
Fire at a target
Observe that view remains on the overmap

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)
