### ISSUE TITLE
All Crew Monitors stop tracking correctly or updating when a Z-level is deleted

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3216]
#### Description of issue
All Crew Monitors stop tracking sensors correctly when a Z-level is deleted, allowing spying on other faction HUDs but also not updating

#### Difference between expected and actual behavior
Crew monitors should be able to track the designated mobs on the same constantly even after a Z-level is deleted

#### Steps to reproduce 
spawn a ship
spawn people with suit sensors on
kill the ship's superstructure health
wait for the Z-level to kill
look back at crew monitor
see as the trackers don't work correctly
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)
