### ISSUE TITLE
Checklist 5/29/2018 - complete like today or tomorrow 

### ISSUE THREAD

**Issue by DoctorOctopusTheOctopi** [HaloSpaceStation/HaloSpaceStation13#625]
- [x] ONI Badge that can morph into a majority of other badges.
- [x] Replace ODST in Research area with ONI Security Guards or some varian, Pending strawpoll results. (https://www.strawpoll.me/15794478)
- [x] Add ONI Security Guard uniforms, armor, ect. **Sprites pending.**
- [x] More loadout items.
- [x] Other stuff I'll forget but when I see I'll know.
- [x] Random things, may include octopi and or octopods.

**Comment by DoctorOctopusTheOctopi** [comment]
Requested by Subdon

- [ ] Berets of MOS. **Sprites pending.**
- [ ] Renamed Medals
- [ ] Uniforms per MOS: Medical,Security, Command, Pilot. **Sprites pending**

**Comment by DoctorOctopusTheOctopi** [comment]
Requested by Gerdes
- [ ] the grey parade hat for unsc captains, 
- [ ] 2 shot glasses
- [ ] a bottle of whiskey
- [ ] premium cigars with a zippo lighter in the captains cabin

**Comment by bloxgate** [comment]
*cough* https://github.com/HaloSpaceStation/HaloSpaceStation13/milestones

**Comment by caelaislinn** [comment]
I'm not adding checklists to milestones. I don't like the idea of personal todo lists as issues either.

**Comment by DoctorOctopusTheOctopi** [comment]
I don't see the problem with it personally. It provides the players an insight into what a specific dev is doing, not only offering transparency but reassurance that said updates will come in the future. Its also no different then a sprite request, or any of the many other issues used as a personal reminder. I also intended for players to post what they wanted here and I would review it and either add it or not.

I can however remove it should you want it removed.

**Comment by caelaislinn** [comment]
1- If a sprite request or feature request is ignored for ages, we can chase up various contributors to do it or simply cancel it. 2- If a contributor takes up a request but does nothing, we can take it back and offer someone else the chance to do it. 

Neither 1) nor 2) are options here. Sprite requests and feature requests anyone can work on. A personal checklist, only one person can. So this issue will clog up the repo because I've never seen an SS13 developer todo list fully finished.

**Comment by bloxgate** [comment]
Perhaps making this a project then?

**Comment by DoctorOctopusTheOctopi** [comment]
Moving this to a personal notepad++ file to clean up issues.
